name: yandex_weather
description: Flutter package to get current weather and weather forecast from Yandex Weather Api.
version: 0.0.1
homepage: https://github.com/artembark/yandex_weather

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  json_annotation: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  json_serializable: ^6.3.1
  build_runner: ^2.2.0

flutter:
